/**
 * Generated by tools/gen-templates.mjs from templates/ — do not edit.
 *
 * Bodies are verbatim: the extension substitutes ${Var} itself (see
 * new-from-template.ts), so no TextMate snippet parsing is involved and `$1`
 * tabstop syntax cannot collide with BBj string variables.
 */

export interface StarterVariable {
    name: string;
    prompt: string;
    default: string;
}

export interface StarterTemplate {
    id: string;
    title: string;
    description: string;
    category: string;
    /** May contain ${Var} placeholders. */
    fileName: string;
    variables: StarterVariable[];
    body: string;
}

export const STARTER_TEMPLATES: StarterTemplate[] = [
    {
        "id": "dwc-browser-program",
        "title": "DWC Browser Program",
        "description": "A minimal BBj program that opens a window with a button and runs in the browser via DWC.",
        "category": "BBj",
        "fileName": "${ProgramName}.bbj",
        "variables": [
            {
                "name": "ProgramName",
                "prompt": "Program name",
                "default": "HelloDWC"
            },
            {
                "name": "WindowTitle",
                "prompt": "Window title",
                "default": "Hello DWC"
            }
        ],
        "body": "REM ${ProgramName}\nREM Generated from the BBj starter catalogue.\nREM Run with \"Run As DWC Program\" (Alt+D).\n\nREM --- Open the SysGui channel --------------------------------------------\nsysgui! = BBjAPI().openSysGui(\"X0\")\n\nREM --- Create the top-level window -----------------------------------------\ntitle$ = \"${WindowTitle}\"\nwindow! = sysgui!.addWindow(50, 50, 400, 220, title$)\nwindow!.setCallback(BBjAPI.ON_CLOSE, \"onClose\")\n\nREM --- Add a button ---------------------------------------------------------\nbutton! = window!.addButton(101, 140, 90, 120, 40, \"Say hello\")\nbutton!.setCallback(BBjAPI.ON_BUTTON_PUSH, \"onButtonPush\")\n\nREM --- Hand control to the event loop ---------------------------------------\nprocess_events\n\nonButtonPush:\n    msg$ = \"Hello from \" + title$ + \"!\"\n    msgbox(msg$, 0, title$)\nreturn\n\nonClose:\n    release\nreturn\n"
    }
];
