package bbj.interop;

public interface JavaLangPackage {
	
	/**
	 * Classes from java.lang package can not be fetched using the default class loader.
	 * Listing them here.
	 */
	public static final String[] JAVA_LANG = (
			// interfaces
			"Appendable\n"
			+ "AutoCloseable\n"
			+ "CharSequence\n"
			+ "Cloneable\n"
			+ "Comparable\n"
			+ "Iterable\n"
			+ "ProcessHandle\n"
			+ "Readable\n"
			+ "Runnable\n"
			// classes
			+ "Boolean\n"
			+ "Byte\n"
			+ "Character\n"
			+ "Class\n"
			+ "ClassLoader\n"
			+ "ClassValue\n"
			+ "Compiler\n"
			+ "Double\n"
			+ "Enum\n"
			+ "Float\n"
			+ "InheritableThreadLocal\n"
			+ "Integer\n"
			+ "Long\n"
			+ "Math\n"
			+ "Module\n"
			+ "ModuleLayer\n"
			+ "Number\n"
			+ "Object\n"
			+ "Package\n"
			+ "Process\n"
			+ "ProcessBuilder\n"
			+ "Record\n"
			+ "Runtime\n"
			+ "RuntimePermission\n"
			+ "SecurityManager\n"
			+ "Short\n"
			+ "StackTraceElement\n"
			+ "StackWalker\n"
			+ "StrictMath\n"
			+ "String\n"
			+ "StringBuffer\n"
			+ "StringBuilder\n"
			+ "System\n"
			+ "Thread\n"
			+ "ThreadGroup\n"
			+ "ThreadLocal\n"
			+ "Throwable\n"
			+ "Void\n"
			// exceptions
			+"ArithmeticException\n"
			+ "ArrayIndexOutOfBoundsException\n"
			+ "ArrayStoreException\n"
			+ "ClassCastException\n"
			+ "ClassNotFoundException\n"
			+ "CloneNotSupportedException\n"
			+ "EnumConstantNotPresentException\n"
			+ "Exception\n"
			+ "IllegalAccessException\n"
			+ "IllegalArgumentException\n"
			+ "IllegalCallerException\n"
			+ "IllegalMonitorStateException\n"
			+ "IllegalStateException\n"
			+ "IllegalThreadStateException\n"
			+ "IndexOutOfBoundsException\n"
			+ "InstantiationException\n"
			+ "InterruptedException\n"
			+ "LayerInstantiationException\n"
			+ "NegativeArraySizeException\n"
			+ "NoSuchFieldException\n"
			+ "NoSuchMethodException\n"
			+ "NullPointerException\n"
			+ "NumberFormatException\n"
			+ "ReflectiveOperationException\n"
			+ "RuntimeException\n"
			+ "SecurityException\n"
			+ "StringIndexOutOfBoundsException\n"
			+ "TypeNotPresentException\n"
			+ "UnsupportedOperationException\n"
			//errors
			+ "AbstractMethodError\n"
			+ "AssertionError\n"
			+ "BootstrapMethodError\n"
			+ "ClassCircularityError\n"
			+ "ClassFormatError\n"
			+ "Error\n"
			+ "ExceptionInInitializerError\n"
			+ "IllegalAccessError\n"
			+ "IncompatibleClassChangeError\n"
			+ "InstantiationError\n"
			+ "InternalError\n"
			+ "LinkageError\n"
			+ "NoClassDefFoundError\n"
			+ "NoSuchFieldError\n"
			+ "NoSuchMethodError\n"
			+ "OutOfMemoryError\n"
			+ "StackOverflowError\n"
			+ "ThreadDeath\n"
			+ "UnknownError\n"
			+ "UnsatisfiedLinkError\n"
			+ "UnsupportedClassVersionError\n"
			+ "VerifyError\n"
			+ "VirtualMachineError"
			).split("\\n");
}
